apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-albumes-config
  namespace: proyecto-sa
data:
  DB_HOST_MS_ALBUMES: "172.17.0.1"
  DB_PORT_MS_ALBUMES: "3306"
  DB_MS_ALBUMES: "MS_PR4_Album"
  PORT_APP_MS_ALBUMES: "5100"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-artistas-config
  namespace: proyecto-sa
data:
  PORT_APP_MS_ARTISTA: "5200"
  DATABASE_URL_MS_ARTISTA: "mysql://root:iskandar@172.17.0.1:3306/MS_PR4_Artista"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-canciones-config
  namespace: proyecto-sa
data:
  PORT_APP_MS_CANCIONES: "5300"
  DATABASE_URL_MS_CANCIONES: "mysql://root:iskandar@172.17.0.1:3306/MS_PR4_Cancion"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-reproducciones-config
  namespace: proyecto-sa
data:
  DB_HOST_MS_REPRODUCCION: "172.17.0.1"
  DB_PORT_MS_REPRODUCCION: "3306"
  DB_MS_REPRODUCCION: "MS_PR4_Reproduccion"
  PORT_APP_MS_REPRODUCCION: "5400"